### ISSUE TITLE
Some important url fixes

### ISSUE THREAD

**Issue by krisv** [apache/incubator-kie-kogito-website#4]
There are a few important url issues that imho need to be fixed short-term:
 * Main page has "learn more" links on 3 places, we do not have this content yet however, the idea was to simply remove those links for now
 * In the footer there is a link to fork the website, I assume that should link to the kogito-website github project instead?
 * The github link in the top right should probably link to the main kogito project: https://github.com/kiegroup/kogito-runtimes

**Comment by adelasofia** [comment]
I've just pushed these fixes on #5
