### ISSUE TITLE
Link to WildFly Swarm near the bottom of the page points to a non-Red Hat website

### ISSUE THREAD

**Issue by somaditya** [apache/incubator-kie-kogito-website#53]
Clicking on WildFly Swarm takes user to https://wildfly-swarm.io/ which is not a Red Hat project page.

It's some Programming Courses website. Maybe the domain changed ownership.

**Comment by somaditya** [comment]
Raised PR https://github.com/kiegroup/kogito-website/pull/54

**Comment by mareknovotny** [comment]
thnx for reporting and fixing it @somaditya
